### ISSUE TITLE
Twig_Function not found

### ISSUE THREAD

**Issue by tekmosis** [akhawaja/TwigView#1]
Followed the setup instructions exactly and receive the following message:

Unhandled Exception

Message:

Class 'Twig_Function' not found
Location:

/projects/raffle/bundles/twigview/Twig/Function/Function.php on line 20

**Comment by akhawaja** [comment]
It appears to me that the Twig_Function class is not being auto-loaded by Laravel.  What version of Laravel are you using?  Also, please post your bundles.php entry.  Thank you.

**Comment by akhawaja** [comment]
Also, what version of TwigView are you using? The last update I made externalized all the configuration. Please also include the contents of config/twig.php in the TwigView bundle. Thanks.

**Comment by akhawaja** [comment]
I am closing this issue in the next few days as I have not received a response.  I am unable to duplicate this issue.

**Comment by akhawaja** [comment]
Closing issue.  No response received.
