### ISSUE TITLE
Requires updating

### ISSUE THREAD

**Issue by ghost** [akhawaja/TwigView#2]
It doesn't appear to work with the current version of Laravel as the Laravel view class underwent  refactoring recently.

**Comment by akhawaja** [comment]
I updated my local dev copy to version 3.1.8 of Laravel and everything seems to work fine.  I also updated TwigView.  Would you please test this again and let me know if it works for you?  Thank you.

**Comment by ghost** [comment]
Unfortunately I am not able to test at the moment as I couldn't find a Twig bundle that worked after the refactoring of the view class so have committed to the the Blade template engine for now. I may revisit this decision in the near future.

Thank you.

**Comment by akhawaja** [comment]
Okay.  Thank you.
